### ISSUE TITLE
Additions to the "Settings" tab

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#104]
In the "Settings" tab on the left sidebar, we need to add the ability for dictionary managers to modify the following settings themselves. This is because we receive a lot of emails from people who want to modify these settings but don't currently have a way to do it without contacting us. 

- ISO Code
- Glottocode
- Location
- Map Coordinates
- Add or remove Glossing Languages 

<img width="1321" alt="Screen Shot 2022-02-11 at 1 25 01 PM" src="https://user-images.githubusercontent.com/17869080/153648654-78fb0a1f-8bb5-4e39-8eb8-b3296e100f0b.png">

Thanks!

**Comment by jacob-8** [comment]
All these features are now live.
