### ISSUE TITLE
Add Rich Text Styling to elements in Entry View

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#110]
Within some cells that people edit inside their entries, we need the rich text styling functionality. We need it to pop up when someone is editing all Glossing Languages, Notes, and Interlinearization fields. 

<img width="690" alt="Where we need rich text styling in Entry View" src="https://user-images.githubusercontent.com/17869080/156243981-2fd68bcf-7500-4b12-b7f1-9bddba89d63f.png">

The rich text styling should appear in the pop-up when people edit the cell:
<img width="1339" alt="where rich text styling component should go" src="https://user-images.githubusercontent.com/17869080/156244709-8014d042-eb00-4d8f-954e-2a200e054247.png">

We already have this functionality available in the “About” section (italics, bold, bullet points, line spacing, hyperlinks, small caps, etc) so the same component should be used again, since it works very well.  See screenshot:
https://livingdictionaries.app/tutelo-saponi/about

<img width="922" alt="Rich text styling component in About section" src="https://user-images.githubusercontent.com/17869080/156244774-ffd749a3-4165-402e-b973-b7bd21b17027.png">

**Comment by AnnaLuisaD** [comment]
Here is what we decided for Rich Text @jacob-8 

- In the glossing language cells, we need add the ability to add ITALICS so that scientific names in Latin can be italicized according to professional biological standards. Only italics is needed, and nothing else. (If you feel like we should have separate data field for scientific name, we should discuss that) 

- In the “Notes” cell, we need the same rich text styling functionality as in the “About” section (italics, bold, bullet points, line spacing, hyperlinks, etc). This will help us make en entry become encyclopedic. For example, I need to add a lot of ethnobotanical information to the entries about Birhor plants. 

- In the interlinearization field, we only need SMALL CAPS, because we need that for Leipzig Glossing Conventions

**Comment by jacob-8** [comment]
For CSV export, convert the notes to plain text, use asterisks surrounding italics in glosses (scientific names) and small-caps will transfer just fine using the solution we came up with to actually use real small-cap letters and not a CSS style adjustment.

**Comment by AnnaLuisaD** [comment]
ok perfect, that sounds very straightforward.

**Comment by AnnaLuisaD** [comment]
hi @jacob-8 :) this particular issue of having rich text in the "Notes" field is now becoming urgent for me. I need to be able to update the "notes" field of the Birhor Living Dictionary with extensive ethnobotanical information around the beginning of June if possible, since it will take me a week or so to complete. I need to get this done before I go on maternity leave, which is rapidly approaching. Also because we are collaborating with MOBOT's Tropicos database on this topic and I need to show them what our content looks like fully fleshed out with the stylized content in the notes field. thanks!
