### ISSUE TITLE
Automatically add speakers.contributingTo when import dictionaries

### ISSUE THREAD

**Issue by Danble** [livingtongues/living-dictionaries#117]
In Birhor we have several speakers:
![image](https://user-images.githubusercontent.com/43384963/157735308-b3a27a21-9360-4660-ac7c-4781adc64d4b.png)
But in the entries that don't have audio files yet, when we try to add one of them, we are not able to see them:
![image](https://user-images.githubusercontent.com/43384963/157735506-bfa0cee8-b28c-4861-8dd7-a8f98d05f32c.png)

That brings me to another question: if a speaker is already a user on our site, don't we need to select him/her instead of create a new one?

**Comment by AnnaLuisaD** [comment]
ok that's a good question. thanks Diego for opening this up again! yes we need to have this issue resolved so that we can fix the Nukuoro Living Dictionary ASAP. I am putting this issue into the "in progress" section

**Comment by Danble** [comment]
Yes, of course! I don't know how we are handling that info, I mean, specifically the createdBy info. But if there's fine for you, I can add my living tongues id as a hardcore id in the script.

**Comment by AnnaLuisaD** [comment]
yes that is a good idea
