### ISSUE TITLE
Add new speaker modal is unable to close in any possible way. You need to refresh the page

### ISSUE THREAD

**Issue by Danble** [livingtongues/living-dictionaries#118]
<img width="1279" alt="Add New Speaker Issues with closing box or cancelling" src="https://user-images.githubusercontent.com/43384963/157736754-498f08fb-be11-4000-ae18-89e823bb36c5.png">

**Comment by AnnaLuisaD** [comment]
yes, we will need this for our team working on the Birhor Living Dictionary. Also we urgently need it for a workshop happening in India on March 24th. there will be around 20 people creating new Living Dictionaries for their languages
