### ISSUE TITLE
Add Alternate Names to Settings

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#129]
Please add a section for Alternate Names. We can re-use the component from the "Create a Dictionary" so that people can continue to add Alternate Names. They should also be able to delete previous names if needed. 

<img width="1147" alt="Add Alternate Names to Settings" src="https://user-images.githubusercontent.com/17869080/159770513-7132b7cd-5847-4601-9176-8a816bda2c3c.png">

**Comment by jacob-8** [comment]
@Danble You could start on this when you have a chance.
