### ISSUE TITLE
Add custom localOrthography field named 'Wancho Laizi' to the Wancho Living Dictionary

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#131]
https://livingdictionaries.app/wancho/entries/list

The dictionary manager has requested to have a data field for a local script. I have been communicating with him. 

email msg from him: "Thank you very much for your help. The name of our script is Wancho script, in our language it is called "Wancho Laizi". The name of unicode fonts are Noto Sans and Noto sans wancho. Kindly add these fonts at earliest. Your contribution will be highly appreciated and acknowledge by our community. 

With best regards
Banwang Losu 

<img width="1203" alt="add new field for localOrthography in this dictionary" src="https://user-images.githubusercontent.com/17869080/160423352-577f4ed3-15b4-4cb8-aabb-19dd1f24e688.png">

**Comment by Danble** [comment]
> our script is Wancho script, in our language it is called "Wancho Laizi". The name of unicode fonts a

@AnnaLuisaD should I add `Wancho Script` or `Wancho Laizi`. 
Please tell Banwang Losu we're not able to use the fonts he is asking for.
