### ISSUE TITLE
New Questions for "Create a Dictionary" Page

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#138]
Just above the "Create a Dictionary" button, please add the following questions and collect the data from the user. The answers should go into the notification email sent us us every time a new Living Dictionary is created. All questions must be answered for the "Create a Dictionary" button to work.

1. Is this dictionary for a language that is spoken or signed by a specific human community? 
[CHECKBOX - they must pick one]
Yes 
No

3. Has the language community given you permission to make this dictionary? 
[RADIO CHECKBOX - they must pick one] - https://svelte.dev/examples/group-inputs
Yes
No
I don’t know

5. Please briefly describe how you know this language and why you are creating a Living Dictionary for it. Are you part of the community that will be using this Living Dictionary? If not, how do you know the community?
[Textbox: LIMIT OF 2500 characters]

6. Is this dictionary for a constructed language (a language invented by humans in recent years, for a book or a movie)? If yes, please briefly describe. 
[Textbox: LIMIT OF 1000 characters]

**Comment by jacob-8** [comment]
@AnnaLuisaD what is the difference between 1 and 4? Are all "No" answers for 1 constructed languages, at which point we can show "Please briefly described the constructed language...etc". What other "No" options for question 1 would we have besides conlangs?

**Comment by jacob-8** [comment]
@Danble Once we resolve my question, you can start in on this one, adding the following properties to the dictionary interface:
```
  languageUsedByCommunity?: Timestamp;
  communityPermission?: Timestamp;
  authorConnection?: string;
  conLangDescription?: string;
```

I'll update after my question is answered.

**Comment by AnnaLuisaD** [comment]
@jacob-8 good question! the reason we ask the #4 question is that we want to be sure to catch the conlangs explicitly in this questionnaire. Some conlangs like Klingon and Elvish (aka Quenya) do have small but enthusiastic human speaker communities that are composed of fans who started learning the languages online through fan forums and publications. So those people might respond "yes" to the first question, yet we don't have any indication they are speaking ocnlangs. 

we do welcome those conlangs on the platform, but want to make sure we know that they are coming onto the platform, and we don't want them to be included on the global language map. We've had a few accidentally show up on the global language map and then people point them out as "fake" languages. I've seen people on Wikipedia bickering about the fact that we let fake languages onto the website, and it seems to undermine our credibility in the minds of some people.

**Comment by jacob-8** [comment]
@AnnaLuisaD the questions are deployed to the live site. The email is not updated yet, but know that any dictionary created from now on, will have the data from those 4 new questions in the database, so keep tabs on which dictionaries are new ones until the email is updated.

**Comment by jacob-8** [comment]
Todo:
- [ ] fix onNewDictionary cloud function in dev and deploy
- [ ] deploy onNewDictionary cloud function to prod after merging PR.

**Comment by jacob-8** [comment]
@Danble this isn't completed until I do those last two tasks.

**Comment by Danble** [comment]
> @Danble this isn't completed until I do those last two tasks.

Ok, sorry. We thought it was ready, but yeah, those pending things are very important. Thanks for letting me know :)

**Comment by jacob-8** [comment]
Info is now on the admin dashboard and email tasks are being tracked in #176
