### ISSUE TITLE
Define language location w/ multiple points and/or polygon regions

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#172]
One of our common requests is that people want to be able to create a polygon for an area where their language is spoken.

However, this requires background research about how to engineer it, and how to display it on the homepage map, and how to display it on the intermediary page map after they click on the dictionary. 

We need a group discussion on this topic, because the situation for each language is quite different. as a team we need to collaborate on the front-end design. it's very much a front-end design consideration issue, so we can take our time with it. 

For example, for Tutelo-Saponi Monacan, we definitely need three geo-pics to identify the area where the language is being revitalization. 

so there three scenarios to contemplate for how to show a language on a map:
1. just one geo-pin (that is what we currently offer)

2. we let them drop multiple geo-pins. but then we need to decide which of those pins are displayed on our homepage? do we allow people browsing our homepage to see the geo-pins displayed in a particular color?

3. we offer the ability to make polygons. then we need to figure out how to display them on our homepage. 

<img width="1493" alt="Screen Shot 2022-05-25 at 3 00 33 PM" src="https://user-images.githubusercontent.com/17869080/170348426-2e50b86c-1f99-4143-9646-4253bee1ed4d.png">

I'll get the specific coordinates for the three places that we are targeting for Tutelo-Saponi Monacan, so we can use those as a test subject.

**Comment by Danble** [comment]
**User interface questions**

- [*] Do you see a scenario where set markers like pins could be useful?
Not yet
- [*] Anna and I think we don’t need to allow users to use layers (polygons), at least not very soon, but do you think it’s important to us to use them?
Internally we can use them but we won't allow public usage
- [*] Do you like labels? Even if I find a way where they are not needed?
Yes, they will be very useful.

I also added the general question although they were already answered by Anna and Greg. But in case you want to do more comments. @jacob-8

**Comment by Danble** [comment]
## Technical questions

- [ ] I didn’t find a way to select a marker by its id or another way. Do you think it is possible? Maybe by an HTML id?

- [ ] Do you think it would be easy to display these new mapbox features on our main map screen?

**Comment by AnnaLuisaD** [comment]
Here is an example of a map website built with Mapbox and OpenStreetMap where they portray overlapping indigenous language communities (in BC, Canada). this is produced by professional cartographers and is not user-generated, as far as I know. it is a map that has evolved a lot over the past 5 years. https://maps.fpcc.ca/
