### ISSUE TITLE
How do we reconcile the multiple instances of "King of Olukumi" in the database?

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#181]
In the Olukumi Living Dictionary, there are currently 34 audio files recorded by a person named "King of Olukumi" who is indeed a real person and fluent speaker of this language. The Olukumi team in Nigeria is getting ready to record a lot more audio this month and I have been training them remotely. As you can see, the King of Olukumi only appears once in the right sidebar. 

https://livingdictionaries.app/olukumi/entries/list

<img width="1334" alt="Screen Shot 2022-06-08 at 2 55 30 PM" src="https://user-images.githubusercontent.com/17869080/172695747-04eabf4c-5a98-4c45-bbb4-b90933de7d06.png">

One weird issue in their dictionary is that when you click on "Add Audio" for an entry, the name for "King of Olukumi" appears a bunch of times in the dropdown. Diego looked at the speaker timestamps in the database and determined that they were all created within seconds or milliseconds of each other. So, there was some type of glitch when the team was creating this profile. Because the electricity and internet in Nigeria is so spotty, the system seems to have created this speaker many times. 

I told the team to make recordings only selecting the top King of Olukumi.

How do we actually reconcile the multiple instances of "King of Olukumi" in the database? I downloaded all 34 audio files just in case we need to delete the speaker and upload his data again.

**Comment by AnnaLuisaD** [comment]
Here is the multitude of Kings of Olukumis as they appear in the dropdown! this issue is not particularly urgent so I am filing it under "Request for Comments"

<img width="1178" alt="Screen Shot 2022-06-08 at 2 51 31 PM" src="https://user-images.githubusercontent.com/17869080/172696615-b2529d26-ff09-46dc-8c44-073671d5ec00.png">

**Comment by AnnaLuisaD** [comment]
Diego can take care of it. Jacob says we could beef up the table view to show the IDs (only to the Admins) and set them all to the same speaker. 
1) So the Table View needs a small edit. 
2) Update speaker add view to be blocking

**Comment by jacob-8** [comment]
@Danble I don't believe that "Table View needs a small edit." has been completed. This should be left open until that is done. Also, have the excess speakers been removed?
