### ISSUE TITLE
Need a "Tutorials" page and new link to it in the top toolbar

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#185]
We need to create a new page where the Tutorial videos will appear as embedded YouTube Videos. 

This page link can also appear in the top menu bar on the homepage and site-wide. We need to locate an icon that symbolizes Tutorials, and of course add it to the translation spreadsheet. 

The new Tutorials page itself can resemble the "About" page. It will have some text and embedded videos.

Here is the first video to embed in English. https://youtu.be/d8neBgRsTrI

Here is the first video to embed in Spanish. https://youtu.be/Mm2-LwKySn8

<img width="1276" alt="Screen Shot 2022-06-15 at 4 01 17 PM" src="https://user-images.githubusercontent.com/17869080/173916830-3fef0611-da82-4d81-b4aa-7636252444c1.png">

**Comment by jacob-8** [comment]
![Image](https://user-images.githubusercontent.com/7559478/189466864-acb430a0-322a-4b61-b3f0-a987360da9f1.png)



![Image](https://user-images.githubusercontent.com/7559478/189466866-1c61447e-f670-4b22-aa14-94e614a27926.png)



![Image](https://user-images.githubusercontent.com/7559478/189466871-141fa0c0-fffa-4901-a96b-e286033f45c6.png)



![Image](https://user-images.githubusercontent.com/7559478/189466878-59f06187-5cef-43da-a44b-f3bb450c1afa.png)

**Comment by jacob-8** [comment]
https://livingdictionaries.app/tutorials

**Comment by jacob-8** [comment]
@Danble Can you please add header.tutorials, "Tutorials" to the i18n spreadsheet and then update the translations in the app? No need to wait for me to merge that change.
