### ISSUE TITLE
Add "Plural Form" field to List View in Sengwer Living Dictionary

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#215]
In this Living Dictionary, can you make a change so that the "Plural Form" field also appears in the List View? Kind of like we did with Babanki. The community has requested it. The data field is used to add more info to the nouns in this language and they want to see that info in the List View.
https://livingdictionaries.app/sengwer/entries/list

Here is an example of a Sengwer entry for a noun
https://livingdictionaries.app/sengwer/entry/u5jGrny2GDbrmAfbqE5T

<img width="742" alt="Screen Shot 2022-09-22 at 1 15 03 PM" src="https://user-images.githubusercontent.com/17869080/191810786-cc88530b-973a-49f5-b0d1-ea584c224454.png">
 that has info in that data field.

**Comment by Danble** [comment]
Done with commit 55d15f46ea4a828f87d5471a27fe2ce52a5157cf
