### ISSUE TITLE
Some sources are treated like hyperlinks even when are not that

### ISSUE THREAD

**Issue by Danble** [livingtongues/living-dictionaries#221]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/43384963/195425447-fa7c3781-fc50-4ede-9bfd-87732df90f59.png">
This is because href has an https part that matches our regex condition: href="Image Source: Arnold Paul, CC BY-SA 2.5 <https://creativecommons.org/licenses/by-sa/2.5>, via Wikimedia Commons"

So the hyperlink jumps to an error page: https://livingdictionaries.app/francais-du-quebec/entry/Image%20Source:%20Arnold%20Paul,%20CC%20BY-SA%202.5%20%3Chttps:/creativecommons.org/licenses/by-sa/2.5%3E,%20via%20Wikimedia%20Commons

**Comment by jacob-8** [comment]
I update svelte-pieces to properly detect URLs within larger strings and return just the URL: https://github.com/jacob-8/kitbook/pull/7 - can you please update to the latest svelte-pieces package to use the changes here? There is no use for our users adding links that are dead so the solution here was to make the link work properly, not to remove it.
