### ISSUE TITLE
Users are not able to delete their new dialects if algolia blocks us

### ISSUE THREAD

**Issue by Danble** [livingtongues/living-dictionaries#306]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/43384963/236284726-67d0e77b-24f3-4cf9-8071-f70a86e78cfe.png">

A user reported the problem in the Hazaragi dictionary, he couldn't remove some dialects and also found it difficult to replace them because he can't see the new dialects when algolia block the new records as it happens at the moment.

In the picture I show how the new dialects are not shown on the modal dialect element because of algolia is blocked right now.

**Comment by jacob-8** [comment]
Solved now that we under the limit
