### ISSUE TITLE
Create dropdown menu in Contact component 

### ISSUE THREAD

**Issue by Danble** [livingtongues/living-dictionaries#333]
Anna and I think that could be really helpful for users and us (admins) to create a dropdown menu in packages\site\src\lib\components\modals\Contact.svelte component, so they can select what type of topic their questions or comments are related with, i.e. delete dictionary, information about batch imports, optional data fields, etc...

It could also be useful if we add that topic as part of the Subject in the emails.

**Comment by jacob-8** [comment]
Go for it
