### ISSUE TITLE
Filter by dialect

### ISSUE THREAD

**Issue by jacob-8** [livingtongues/living-dictionaries#38]

**Comment by Danble** [comment]
Check Opata LD

**Comment by AnnaLuisaD** [comment]
For example, a Dialect filter would be great, appearing somewhere on the right sidebar. This dictionary has around 4 or 5 different dialects (Tonichi, Eudeve, Teguima, etc) so it would be good it users can filter the content by the different dialects. Not sure how that would work in the database. https://livingdictionaries.app/opata/entries/list

<img width="1429" alt="Opata Living Dictionary" src="https://user-images.githubusercontent.com/17869080/158668089-2b12b597-eae4-4530-a868-642737bd8650.png">
