### ISSUE TITLE
Print View

### ISSUE THREAD

**Issue by jacob-8** [livingtongues/living-dictionaries#43]
Started in #203
- [x] Automatically save selected print settings to localStorage the same way we do table view's columns so that users can pick up where they left off next time they come. This process will make automatically include adding i18n to the field checkboxes.
- [x] Set up 6-10 test cases in Kitbook for easy design adjustments (place test data in sibling file to not clutter up the story file)
- [x] Add option in settings to allow general public access to the print view - add `publicPrint?: boolean;` to the dictionary interface

 and released in #222 with:
- [x] Toggle labels button
- [x] Restore labels for fields that are not straightforward to be found in entries (images)
- [x] print headers/footers content
- [x] Remove admin blocks

Needs further improvements:
- [x] Diego: add entry.id to i18n spreadsheet, and make sure all other i18n needs are taken care of

Formerly called "PDF export" - I think "Print View" is a better way of framing this task as sometimes people want to print PDFs, sometimes they want to print straight to the printer. In a world of modern browsers where I can even create PDFs from the print function on my cell phone, it's better to provide a flexible print view and let users use the very robust platform features to print PDFs exactly as desired (booklet, letter, A4, A3, etc). This will make our code lighter and will give users more features at less cost to us.

**Comment by AnnaLuisaD** [comment]
Greg has a lot of thoughts and background on formatting for PDF

**Comment by Danble** [comment]
@jacob-8 I added two more changes in this PRs:

1. Citation is ready
2. I had forgotten to add some i18n texts in the EntryDisplay components, so I fixed it.

**Comment by AnnaLuisaD** [comment]
@jacob-8 Marty volunteers to help on formatting the headers and footers if you need a hand anytime. You can also brainstorm with him if there is anything else related to Print View that needs help. He worked a lot in the printing design world before doing web dev so he may have some insights if needed.

I am adding this info here from our Slack channel, pertaining to the header and the footer. 

HEADER: The name of the Living Dictionary. for example “Apatani Living Dictionary”

FOOTER: Only the citation of the dictionary. Diego will add an editable string box so we can have the authors at the beginning of the citation. for example, this dictionary will become:

Anderson et al., 2022. Apatani Living Dictionary. Living Tongues Institute for Endangered Languages. https://livingdictionaries.app/apatani (edited)

**Comment by AnnaLuisaD** [comment]
@jacob-8 @Danble My last thought on the topic of headers and footers is that if it's too complicated to display them into the Print View, then we just need to add a clear, concise and easy-to-translate instruction somewhere on the screen instructing people to activate their "header and footer" in their browser's printing modal that pops up. Something like:

**To include the dictionary's title and citation to your PDF, activate the "show header and footer" box in your print settings before proceeding to print.**

**Comment by jacob-8** [comment]
Closing first chapter of print entry - further improvements will continue to be made down the road.
