### ISSUE TITLE
Repair and merge duplicate speakers

### ISSUE THREAD

**Issue by AnnaLuisaD** [livingtongues/living-dictionaries#434]
In some of the Living Dictionaries from India, we have speakers with multiple profiles that have slightly different spellings. These need to be reconciled under one correct spelling. These corrections have been approved by Greg Anderson, who worked directly with these speakers. 

In the [Gutob Living Dictionary](https://livingdictionaries.app/gutob/entries/list) there are two speakers to repair: 
~~Kamla Sisa, Komla Sisa~~ ---> **Kamla Sisa** (speaker metadata required)
~~Tonkodhar Sisa, Tonkhodhar Sisa, Tonkhodar Sisa~~ ---> **Tonkodar Sisa** (speaker metadata required)

~~In the [Sora Living Dictionary](https://livingdictionaries.app/sora/entries/list), Opino appears twice, and one instance has a typo in the first name (there is an extra g that does not belong here):
Opingo Gomango, Opino Gomango ---> **Opino Gomango**~~

In the [Gta' Living Dictionary](https://livingdictionaries.app/gta/entries/list) there is one speaker to repair:
~~Budura Raspeda~~ ---> **Budra Raspeda** (speaker metadata required)

Thanks!

**Comment by Danble** [comment]
[Itonama Living Dictionary](https://livingdictionaries.app/itonama): Data from Mariana Huasanilla.

**Comment by Danble** [comment]
> In some of the Living Dictionaries from India, we have speakers with multiple profiles that have slightly different spellings. These need to be reconciled under one correct spelling. These corrections have been approved by Greg Anderson, who worked directly with these speakers.
> 
> In the [Gutob Living Dictionary](https://livingdictionaries.app/gutob/entries/list) there are two speakers to repair: Kamla Sisa, Komla Sisa ---> **Kamla Sisa** Tonkhodhar, Tonkhodar, Tonkhodar ---> **Tonkodar Sisa**
> 
> In the [Sora Living Dictionary](https://livingdictionaries.app/sora/entries/list), Opino appears twice, and one instance has a typo in the first name (there is an extra g that does not belong here): Opingo Gomango, Opino Gomango ---> **Opino Gomango**
> 
> In the [Gta' Living Dictionary](https://livingdictionaries.app/gta/entries/list) there is one speaker to repair: Budra Raspeda, Budura Raspeda ---> **Budra Raspeda**
> 
> Thanks!

@AnnaLuisaD Just need the speaker metadata of Kamla Sisa &

**Comment by AnnaLuisaD** [comment]
Tonkodhar Sisa, male, 20 years old, India
Kamla Sisa, female, 20 years old, India
Budra Sisa, male, 20 years old, India

**Comment by AnnaLuisaD** [comment]
Candelaria Huacama Hualasua, female, 65
hometown: Magdalena, Beni, Bolivia

Simona Sejas Huatiya, female, 80
hometown: Magdalena, Beni, Bolivia

Mariana Huasanilla Cabao, female, 75
hometown: Magdalena, Beni, Bolivia

**Comment by AnnaLuisaD** [comment]
Aewa speaker info:

Delia Andi Macahuachi, female, 80
hometown: Puerto Elvira, Loreto, Peru
