### ISSUE TITLE
Further export improvements

### ISSUE THREAD

**Issue by jacob-8** [livingtongues/living-dictionaries#67]
Refactor together:

- [x] continue expanding tests with larger entry inputs to make refactoring worry-free
- [x] use already established naming conventions (sf (soundfile) instead of au, pf (photofile) instead of im)
- [x] put quotes around items that have commas instead of pulling out all commas and just do it at the end.
- [x] Add a formattedEntry type interface
- [x] Don't use JSON.parse and Object.assign when it makes code more verbose for no benefit

Other items:
- [x] don't fetch all speakers - just get ones for current dictionary
- [ ] ~~XSLX option (see git history for HTML code that got removed)~~
- [x] #71

**Comment by jacobbowdoin** [comment]
Odd files to inspect:
Háusi Kúta .m4a files

![image](https://user-images.githubusercontent.com/7559478/140754105-a75e8c21-3ec0-417c-8e35-e8b83725ca1f.png)

**Comment by Danble** [comment]
@jacob-8 the suggested improvement of add a formattedEntry type interface is due to this?
![image](https://user-images.githubusercontent.com/43384963/170383558-5af9e6f3-0151-4a31-9f45-2e4458b53bc9.png)
Is because you want to use a IFormattedEntry type instead of any?

**Comment by jacob-8** [comment]
> you want to use a IFormattedEntry type instead of any?

Yes, if possible, avoid using the "any" type. Always provide a type interface when working on code that is entirely written by us. Sometimes if you are using a library that is not typed, you may have to occasionally use "any", but in a case where we are transforming the shape of data, it is critical to also type things.
