### ISSUE TITLE
Update Email Sending Tool

### ISSUE THREAD

**Issue by jacob-8** [livingtongues/living-dictionaries#72]
Because of rapid growth, we need to find a more robust email sending solution.

Because our email volume often approaches (and sometimes goes over) the soft limit of 100 emails per month, if we stay with SendGrid we are forced to pay $14/mo to continue using their service. Not horrendous in the short-run, but overpriced in the long run, considering services like Amazon SES charge 1 penny per 100 emails sent.

Even better MailChannels (largest email sending service out there) offers a very lightweight and simple method to send unlimited emails for free. See https://blog.mailchannels.com/mailchannels-enables-free-email-sending-for-cloudflare-workers-customers

Tasks:

- [x] Investigate options: AWS, MailChannels
- [x] Move templates out of SendGrid and into HTML email mocking tool: [New User](https://sveed.dev/FAQF818OLoOHtK5XLj5n/api), [New Dictionary](https://sveed.dev/8AgmXjXqXEyXlOwPCWnz/api)
- [x] Document how to allow users to update email address, add a login provider, delete account, authenticate current email
- [x] #183  - with having a wider and wider network, it's becoming increasingly more critical to ensure people are using legitimate emails they own and also have not typoed their email, thus keeping us from ever contacting them.
- [x] Update email sending functions (in progress): 1) #176 , 2) [Worker sender](https://mailchannels.zendesk.com/hc/en-us/articles/4565898358413-Sending-Email-from-Cloudflare-Workers-using-MailChannels-Send-API)

**Comment by jacob-8** [comment]
> hi! is this is the issue related to being able to send Diego notifications at his email address?

Yes

**Comment by AnnaLuisaD** [comment]
ok thank you! gotcha

**Comment by AnnaLuisaD** [comment]
Awaiting update from Jacob on this topic at today's group meeting. Hopefully if we can make sure Diego starts getting the emails by June 30th, that would be great for Anna's maternity leave. All notifications, including "Living Dictionaries Support Requests"
